### ISSUE TITLE
Fine-tune documentaiton

### ISSUE THREAD

**Issue by derekrodgers** [UBC-MDS/Dynamic33#18]
Someone should go through analysis as described in our documentation and make sure they can reproduce it without help. If not, we should make it more verbose. We can discuss deficencies and suggested fixes here, then tag PRs that fix the documentation.

**Comment by ZhengHe-007** [comment]
I'll work on this problem

**Comment by ZhengHe-007** [comment]
I have encountered a lot of issues on installing packages after running renv::restore() in my r console, for example: Error: Error installing package 'nlme':
================================

* installing *source* package ‘nlme’ ...
** package ‘nlme’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C compiler: ‘Apple clang version 14.0.3 (clang-1403.0.22.14.1)’
sh: /opt/gfortran/bin/gfortran: No such file or directory
using SDK: ‘MacOSX13.3.sdk’
/opt/gfortran/bin/gfortran -arch arm64  -fPIC  -Wall -g -O2  -c chol.f -o chol.o
make: /opt/gfortran/bin/gfortran: No such file or directory
make: *** [chol.o] Error 1
ERROR: compilation failed for package ‘nlme’
* removing ‘/Users/zheng/Downloads/Dynamic33/renv/staging/1/nlme’
------------------------------------------------------------------------------ 
R was unable to find the gfortran binary.
gfortran is required for the compilation of FORTRAN source files.
Please check that gfortran is installed and available on the PATH.
Please see https://stackoverflow.com/q/35999874 for more information.

Reason(s):
- 'sh: /opt/gfortran/bin/gfortran: No such file or directory'
- 'make: /opt/gfortran/bin/gfortran: No such file or directory'
install of package 'nlme' failed [error code 1]

But we already can run the analysis and knit to pdf in the container

**Comment by derekrodgers** [comment]
After getting help from Tiffany, we've moved away from renv. Instead, now we are using the `rocker/verse` base container along with the `install2.r` command in a `RUN` line in the Dockerfile.

This solves all of the issues relating to renv. Since we are now all moving to working directly in the container, it will no longer be an issue. The container was implemented in #19 .

**Comment by derekrodgers** [comment]
I've added a complete set of instructions for running the docker image and reproducing the analysis inside the container in #22 , so this should now be resolved.

**Comment by derekrodgers** [comment]
I've added a complete set of instructions for running the docker image and reproducing the analysis inside the container in #22  , so this should now be resolved.
