### ISSUE TITLE
Put analysis code in a directory

### ISSUE THREAD

**Issue by derekrodgers** [UBC-MDS/Dynamic33#26]
Put analysis code in a directory

We had a point deducted for:
```
The analysis notebook (.ipynb or .Qmd or *Rmd) should be in a sub-directory called something sensible, such as analysis, src, notebooks, docs, etc, to aid in the discoverability of this file, and related ones. Having too many files in the project root makes the project organization less understandable and can lead to longer activation times to productivity for collaborators (including future you!).
```

**Comment by gunishakaur** [comment]
The analysis notebook is  in the sub directory report !

**Comment by derekrodgers** [comment]
FYI, no, the code itself is in scripts/. Only the qmd is in report/

But we are moving it to R/ for this milestone which is what Daniel said we should do. Either way we're fine

**Comment by derekrodgers** [comment]
No, it does not need to be reopened. As I said:
> But we are moving it to R/ for this milestone which is what Daniel said we should do. Either way we're fine

I've already done it 👍
